[2023-04-23T13:52:44.604+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_script_to_GCS scheduled__2023-04-11T00:00:00+00:00 [None]>
[2023-04-23T13:52:44.622+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_script_to_GCS scheduled__2023-04-11T00:00:00+00:00 [None]>
[2023-04-23T13:52:44.624+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T13:52:44.626+0000] {taskinstance.py:1289} INFO - Starting attempt 5 of 7
[2023-04-23T13:52:44.627+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T13:52:44.645+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_script_to_GCS> on 2023-04-11 00:00:00+00:00
[2023-04-23T13:52:44.655+0000] {standard_task_runner.py:55} INFO - Started process 4892 to run task
[2023-04-23T13:52:44.658+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_script_to_GCS', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '1200', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpbmrgi7fx']
[2023-04-23T13:52:44.661+0000] {standard_task_runner.py:83} INFO - Job 1200: Subtask task_script_to_GCS
[2023-04-23T13:52:44.745+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_script_to_GCS scheduled__2023-04-11T00:00:00+00:00 [running]> on host 235fa867d994
[2023-04-23T13:52:44.817+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_script_to_GCS
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-23T13:52:44.822+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-23T13:52:44.825+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gsutil -m cp -r -f /opt/***/code/ gs://nfl-data-lake_nfl-project-de/']
[2023-04-23T13:52:44.841+0000] {subprocess.py:86} INFO - Output:
[2023-04-23T13:52:50.309+0000] {subprocess.py:93} INFO - CommandException: Incorrect option(s) specified. Usage:
[2023-04-23T13:52:50.310+0000] {subprocess.py:93} INFO - 
[2023-04-23T13:52:50.311+0000] {subprocess.py:93} INFO -   gsutil cp [OPTION]... src_url dst_url
[2023-04-23T13:52:50.312+0000] {subprocess.py:93} INFO -   gsutil cp [OPTION]... src_url... dst_url
[2023-04-23T13:52:50.313+0000] {subprocess.py:93} INFO -   gsutil cp [OPTION]... -I dst_url
[2023-04-23T13:52:50.314+0000] {subprocess.py:93} INFO - 
[2023-04-23T13:52:50.315+0000] {subprocess.py:93} INFO - For additional help run:
[2023-04-23T13:52:50.316+0000] {subprocess.py:93} INFO -   gsutil help cp
[2023-04-23T13:52:50.752+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-23T13:52:50.763+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 216, in task_script_to_GCS
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-23T13:52:50.778+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_script_to_GCS, execution_date=20230411T000000, start_date=20230423T135244, end_date=20230423T135250
[2023-04-23T13:52:50.802+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1200 for task task_script_to_GCS (Bash command failed. The command returned a non-zero exit code 1.; 4892)
[2023-04-23T13:52:50.827+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T13:52:50.844+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
