[2023-04-12T10:24:37.215+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gsutil_example.copy_local_to_gcs manual__2023-04-12T10:24:32.546336+00:00 [queued]>
[2023-04-12T10:24:37.230+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gsutil_example.copy_local_to_gcs manual__2023-04-12T10:24:32.546336+00:00 [queued]>
[2023-04-12T10:24:37.231+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T10:24:37.233+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-12T10:24:37.234+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T10:24:37.257+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): copy_local_to_gcs> on 2023-04-12 10:24:32.546336+00:00
[2023-04-12T10:24:37.274+0000] {standard_task_runner.py:55} INFO - Started process 2508 to run task
[2023-04-12T10:24:37.278+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsutil_example', 'copy_local_to_gcs', 'manual__2023-04-12T10:24:32.546336+00:00', '--job-id', '818', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpndr7inzx']
[2023-04-12T10:24:37.281+0000] {standard_task_runner.py:83} INFO - Job 818: Subtask copy_local_to_gcs
[2023-04-12T10:24:37.360+0000] {task_command.py:389} INFO - Running <TaskInstance: gsutil_example.copy_local_to_gcs manual__2023-04-12T10:24:32.546336+00:00 [running]> on host a2e619923d04
[2023-04-12T10:24:37.441+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gsutil_example
AIRFLOW_CTX_TASK_ID=copy_local_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T10:24:32.546336+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T10:24:32.546336+00:00
[2023-04-12T10:24:37.444+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T10:24:37.448+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gsutil cp -r /opt/***/csv/ gs://nfl-data-lake_nfl-de-project/nfl_csv']
[2023-04-12T10:24:37.467+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T10:24:43.673+0000] {subprocess.py:93} INFO - ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
[2023-04-12T10:24:44.107+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T10:24:44.127+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T10:24:44.144+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=gsutil_example, task_id=copy_local_to_gcs, execution_date=20230412T102432, start_date=20230412T102437, end_date=20230412T102444
[2023-04-12T10:24:44.174+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 818 for task copy_local_to_gcs (Bash command failed. The command returned a non-zero exit code 1.; 2508)
[2023-04-12T10:24:44.213+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T10:24:44.237+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
