[2023-04-12T04:52:03.866+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-12T04:20:33.394748+00:00 [queued]>
[2023-04-12T04:52:03.884+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-12T04:20:33.394748+00:00 [queued]>
[2023-04-12T04:52:03.885+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:52:03.887+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-12T04:52:03.888+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:52:03.912+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_teams_stats> on 2023-04-12 04:20:33.394748+00:00
[2023-04-12T04:52:03.930+0000] {standard_task_runner.py:55} INFO - Started process 1962 to run task
[2023-04-12T04:52:03.962+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_teams_stats', 'manual__2023-04-12T04:20:33.394748+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp30yzeaue']
[2023-04-12T04:52:03.999+0000] {standard_task_runner.py:83} INFO - Job 287: Subtask task_teams_stats
[2023-04-12T04:52:04.402+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-12T04:20:33.394748+00:00 [running]> on host 392d142fd52f
[2023-04-12T04:52:04.609+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_teams_stats
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T04:20:33.394748+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T04:20:33.394748+00:00
[2023-04-12T04:52:04.627+0000] {logging_mixin.py:137} INFO - Fetching for teams_stats started
[2023-04-12T04:52:06.611+0000] {logging_mixin.py:137} INFO - Fetching for team_stats ended
[2023-04-12T04:52:06.612+0000] {python.py:177} INFO - Done. Returned value was:                     name  ... teamId
0                fumbles  ...      5
1            fumblesLost  ...      5
2          fumblesForced  ...      5
3       fumblesRecovered  ...      5
4      fumblesTouchdowns  ...      5
...                  ...  ...    ...
8027  totalTwoPointConvs  ...     20
8028   twoPointPassConvs  ...     20
8029    twoPointRecConvs  ...     20
8030   twoPointRushConvs  ...     20
8031   onePtSafetiesMade  ...     20

[8032 rows x 13 columns]
[2023-04-12T04:52:06.661+0000] {xcom.py:629} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-04-12T04:52:06.663+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2298, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-04-12T04:52:06.677+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_extraction_dag, task_id=task_teams_stats, execution_date=20230412T042033, start_date=20230412T045203, end_date=20230412T045206
[2023-04-12T04:52:06.699+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 287 for task task_teams_stats (Object of type DataFrame is not JSON serializable; 1962)
[2023-04-12T04:52:06.749+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T04:52:06.778+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
