[2023-04-12T10:20:19.055+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gsutil_example.copy_local_to_gcs manual__2023-04-12T10:20:13.514510+00:00 [queued]>
[2023-04-12T10:20:19.069+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gsutil_example.copy_local_to_gcs manual__2023-04-12T10:20:13.514510+00:00 [queued]>
[2023-04-12T10:20:19.070+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T10:20:19.072+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-12T10:20:19.073+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T10:20:19.093+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): copy_local_to_gcs> on 2023-04-12 10:20:13.514510+00:00
[2023-04-12T10:20:19.108+0000] {standard_task_runner.py:55} INFO - Started process 2059 to run task
[2023-04-12T10:20:19.113+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsutil_example', 'copy_local_to_gcs', 'manual__2023-04-12T10:20:13.514510+00:00', '--job-id', '816', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmptytnltt0']
[2023-04-12T10:20:19.119+0000] {standard_task_runner.py:83} INFO - Job 816: Subtask copy_local_to_gcs
[2023-04-12T10:20:19.218+0000] {task_command.py:389} INFO - Running <TaskInstance: gsutil_example.copy_local_to_gcs manual__2023-04-12T10:20:13.514510+00:00 [running]> on host a2e619923d04
[2023-04-12T10:20:19.311+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gsutil_example
AIRFLOW_CTX_TASK_ID=copy_local_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T10:20:13.514510+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T10:20:13.514510+00:00
[2023-04-12T10:20:19.314+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T10:20:19.319+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gsutil cp -r /opt/***/csv/ gs://nfl-data-lake_nfl-de-project/nfl_csv']
[2023-04-12T10:20:19.338+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T10:20:25.603+0000] {subprocess.py:93} INFO - ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
[2023-04-12T10:20:26.122+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T10:20:26.137+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T10:20:26.144+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=gsutil_example, task_id=copy_local_to_gcs, execution_date=20230412T102013, start_date=20230412T102019, end_date=20230412T102026
[2023-04-12T10:20:26.191+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 816 for task copy_local_to_gcs (Bash command failed. The command returned a non-zero exit code 1.; 2059)
[2023-04-12T10:20:26.216+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T10:20:26.243+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
