[2023-04-12T09:17:16.612+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_athletes manual__2023-04-12T09:16:47.753380+00:00 [queued]>
[2023-04-12T09:17:16.629+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_athletes manual__2023-04-12T09:16:47.753380+00:00 [queued]>
[2023-04-12T09:17:16.630+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T09:17:16.631+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-12T09:17:16.632+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T09:17:16.654+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_athletes> on 2023-04-12 09:16:47.753380+00:00
[2023-04-12T09:17:16.668+0000] {standard_task_runner.py:55} INFO - Started process 4783 to run task
[2023-04-12T09:17:16.677+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_athletes', 'manual__2023-04-12T09:16:47.753380+00:00', '--job-id', '696', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp0lxuwnev']
[2023-04-12T09:17:16.688+0000] {standard_task_runner.py:83} INFO - Job 696: Subtask task_athletes
[2023-04-12T09:17:16.820+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_athletes manual__2023-04-12T09:16:47.753380+00:00 [running]> on host a2e619923d04
[2023-04-12T09:17:17.029+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_athletes
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T09:16:47.753380+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T09:16:47.753380+00:00
[2023-04-12T09:17:17.034+0000] {logging_mixin.py:137} INFO - Fetching for athlete details started
[2023-04-12T09:17:31.926+0000] {local_task_job.py:276} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-04-12T09:17:31.931+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 4783. PIDs of all processes in the group: [4783]
[2023-04-12T09:17:31.932+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4783
[2023-04-12T09:17:31.959+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-12T09:17:32.347+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4783, status='terminated', exitcode=0, started='09:17:16') (4783) terminated with exit code 0
